title: Samantha Adler
description: "Basic Responsive Template for Jekyll using Bootstrap"

url: http://samadler.github.io/
# baseurl: ""
# paginate_path: "blog/page:num/"
# permalink: blog/:title/

markdown: redcarpet

sass:
   sass_dir: _sass
   style: :compressed

navigation:
 - title: About
   url: /
 - title: Work
   url: /
 - title: Photography
   url: /photography/
 - title: Contact
   url: /contact/


social:
   github: samadler
   email: samantha.m.adler@gmail.com

prose:
   media: "assets/img"